POST http://localhost:5000/v1/user
Content-Type: application/json

{
  "userName" : "kai56555" ,
  "email" : "kaizejasdfkjas@gmail.com" ,
  "fullName" : "Vikas Sandhu",
  "password" : "vistagram@123"
}

###
GET http://localhost:5000/v1/user/email/kaizen.tech404@gmail.com/verify

###
POST http://localhost:5000/v1/user/email/verify
Content-Type: application/json

{
  "verificationToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyNTBmMWUzYy1lNDJlLTQyMmUtYjUyNC05MDZiMWM5OTI1ZTIiLCJpYXQiOjE2MTg2ODIzNTksImV4cCI6MTYxODY4MjcxOX0.Vc_VPE_ZQMJdzhzU2YBLkxNFmY0qcg5J_qNxv2_1h-s"
}

###
POST http://localhost:5000/v1/user/login
Content-Type: application/json

{
  "email" : "kaizen2323t.tdsaf4@gmail.com" ,
  "password" : "vistagram@123"
}

###
GET http://localhost:5000/v1/user
