POST http://localhost:5000/v1/user
Content-Type: application/json

{
  "userName" : "kai56555" ,
  "email" : "kaizejasdfkjas@gmail.com" ,
  "firstName" : "Vikas",
  "lastName" : "Sandhu",
  "password" : "vistagram@123"
}

###
GET http://localhost:5000/v1/user/email/kawai@gmail.com/verify

###
POST http://localhost:5000/v1/user/email/verify
Content-Type: application/json

{
  "verificationToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4N2M4MGFmYS02MmQ5LTRkYjctYTQ1NC1mNWIxMjYwMDI3ZTciLCJpYXQiOjE2MjAyOTc1NjUsImV4cCI6MTYyMDI5NzkyNX0.bIJdeiTKpQEDJrC3h7wJsbvTKbZfac5BOU1oPUvAUzI"
}

###
POST http://192.168.43.159:5000/v1/user/login
Content-Type: application/json

{
  "email" : "vikassandhu999@gmail.com" ,
  "password" : "instagram@123"
}

###
GET http://localhost:5000/v1/user


###
GET http://192.168.43.159:5000/v1/storage/upload-link?fileExtension=jpeg&fileType=image/png