POST http://localhost:5000/v1/user
Content-Type: application/json

{
  "userName" : "kai56555" ,
  "email" : "kaizejasdfkjas@gmail.com" ,
  "firstName" : "Vikas",
  "lastName" : "Sandhu",
  "password" : "vistagram@123"
}

###
GET http://localhost:5000/v1/user/email/kaizejasdfkjas@gmail.com/verify

###
POST http://localhost:5000/v1/user/email/verify
Content-Type: application/json

{
  "verificationToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxY2Y3ZTMzNS03MjYwLTRiYzktOTBkOC01ZGI1NDYzMWExNGUiLCJpYXQiOjE2MjAyMjc3NDgsImV4cCI6MTYyMDIyODEwOH0.X1QzfYRY1CwC5IS-9j7fvZmfab5kUQPlSDGnmF2U5C0"
}

###
POST http://localhost:5000/v1/user/login
Content-Type: application/json

{
  "email" : "kaizejasdfkja@gmail.com" ,
  "password" : "vistagram@123"
}

###
GET http://localhost:5000/v1/user
